apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql3
  namespace: micro-services
spec:
  serviceName: mysql3
  replicas: 2
  selector:
    matchLabels:
      app: mysql3
  template:
    metadata:
      labels:
        app: mysql3
    spec:
      containers:
        - name: mysql3
          image: mysql:9
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db_password
            - name: MYSQL_PASSWORD # Set password for root1 user
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db_password # Password for root1 user
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: sql-scripts3
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: sql-scripts3
          configMap:
            name: mysql-init-scripts3
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts3
  namespace: micro-services
data:
  commande_dump.sql: |
    CREATE DATABASE IF NOT EXISTS `panier` ;
    USE `panier`;

     DROP TABLE IF EXISTS `panier`;
     CREATE TABLE `panier` (
       `id` int NOT NULL AUTO_INCREMENT,
       `item_details` tinytext NOT NULL,
      `disponibilité` tinyint(1) DEFAULT NULL,
      `quantité` int NOT NULL,
       `prix` double NOT NULL,
       `a_retirer` timestamp NULL DEFAULT NULL,
       `nom_panier` varchar(255) DEFAULT NULL,
       PRIMARY KEY (`id`)
     ) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
     


     LOCK TABLES `panier` WRITE;

     INSERT INTO `panier` VALUES (1,'Pommes, bananes',1,6,2.99,'2025-01-04 14:48:24','Fruits '),(2,'Pain, tartes, croissants',1,8,3.49,'2025-01-11 14:43:49','Patisserie ');

     UNLOCK TABLES;

---
apiVersion: v1
kind: Service
metadata:
  name: mysql3
  namespace: micro-services
spec:
  selector:
    app: mysql3
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-panier
  namespace: micro-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-panier
  template:
    metadata:
      labels:
        app: ms-panier
    spec:
      containers:
        - name: panier
          image: idriss5234/ms_panier:latest
          ports:
            - containerPort: 8091
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db_username # root1 user from secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db_password # root1 password from secret
---
apiVersion: v1
kind: Service
metadata:
  name: ms-panier
  namespace: micro-services
spec:
  selector:
    app: ms-panier
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: NodePort
