version: "3.8"
services:
  mysql2:
    container_name: mysql2
    image: mysql:8.4.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306" # Mapping 3306 inside the container to 3307 on the host
    networks:
      - micro-services
    volumes:
      - ./commande_dump.sql:/docker-entrypoint-initdb.d/commande_dump.sql
    command: --init-file /docker-entrypoint-initdb.d/commande_dump.sql

  commande:
    image: idriss5234/ms_commande:latest
    container_name: commande
    restart: always
    ports:
      - "9092:8092"
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - micro-services
    depends_on:
      - mysql2

networks:
  micro-services:
    external: true
