version: "3.8"
services:
  mysql3:
    image: mysql:8.4.4
    container_name: mysql3
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - micro-services
    volumes:
      - ./panier_dump.sql:/docker-entrypoint-initdb.d/panier_dump.sql #OPTIONEL!!, nous voulons migrer notre ancienne base de données c"st pourquoi on a utilisé ce volume

  panier:
    image: idriss5234/ms_panier:latest
    container_name: panier
    restart: always
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "9091:8091"
    networks:
      - micro-services
    depends_on:
      - mysql3

networks:
  micro-services:
    external: true
